---
title: '**MTH375**: Mathematical Statistics - Homework #1'
output:
  pdf_document:
    latex_engine: pdflatex
    extra_dependencies:
    - xcolor
    - hyperref
    - graphicx
    - amsmath
    - bm
  word_document: default
  html_document:
    df_print: paged
fontsize: 12pt
wrap: auto
graphics: yes
ipynb-output: best
metadata:
  author:
  - Cason Konzer
standalone: true
---

```{=latex}
\begin{center}
  \color{violet}\textit{\large{\href{https://github.com/casonk}{Cason Konzer}}}\color{black} \\
\end{center}
\hrulefill
```

```{=latex}
\vfill 
    \underline{Key Concepts}:  Multivariate normal({$\bm{\mu},\Sigma)$, $\chi^2$ with $n$ df, $t$ with $n$ df, $F$ with $m,n$ df
\newpage
```

```{r include=FALSE}
options(knitr.graphics.error = FALSE)

library(knitr)
library(ggplot2)

def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

```{=latex}
1.  Suppose that $Z_1,Z_2$ are independent standard normal random variables.  

\noindent Let $Y_1=Z_1-2Z_2$, $Y_2=Z_1-Z_2$.

\hrulefill 
```

```{=latex}
(a)  Find the joint pdf $f_{Y_1,Y_2}(y_1,y_2)$. \ \ 

You may do this either of two ways.  Either (i) use the change of variables theorem from MTH 372, OR   (ii)  evaluate the matrices  $\Sigma$ and $\Sigma^{-1}$ from class, then multiply the necessary matrices and vectors to obtain a formula for  $f_{Y_1,Y_2}(y_1,y_2)$. In either case, obtain a formula containing no matrices and no vectors.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
We have a system of equations, $\displaystyle 
\bm{Y} = 
\begin{bmatrix}
Y_{1} \\
Y_{2}
\end{bmatrix} = A\bm{Z} + \bm{\mu} =
\begin{bmatrix}
1 & -2 \\
1 & -1
\end{bmatrix}
\begin{bmatrix}
Z_{1} \\
Z_{2}
\end{bmatrix} + 
\begin{bmatrix}
0 \\
0
\end{bmatrix}
$.
\vspace{5mm}
\\
We can solve for $ \displaystyle 
\bm{\Sigma} = \bm{AA^{T}} =
\begin{bmatrix}
1 & -2 \\
1 & -1
\end{bmatrix}
\begin{bmatrix}
1 & 1 \\
-2 & -1
\end{bmatrix} = 
\begin{bmatrix}
5 & 3 \\
3 & 2
\end{bmatrix} = \bm{\Sigma}
$.
\vspace{5mm}
\\
We can now evaluate $ \displaystyle 
\bm{\Sigma}^{-1}.
\vspace{5mm}
\\
\begin{bmatrix}
5 & 3 & 1 & 0 \\
3 & 2 & 0 & 1
\end{bmatrix} = 
\begin{bmatrix}
10 & 6 & 2 & 0 \\
3 & 2 & 0 & 1
\end{bmatrix} = 
\begin{bmatrix}
1 & 0 & 2 & -3 \\
3 & 2 & 0 & 1
\end{bmatrix} = 
\begin{bmatrix}
1 & 0 & 2 & -3 \\
0 & 2 & -6 & 10
\end{bmatrix} = 
\begin{bmatrix}
1 & 0 & 2 & -3 \\
0 & 1 & -3 & 5
\end{bmatrix}
$.
\vspace{5mm}
\\
Our solution yields $ \displaystyle 
\bm{\Sigma}^{-1} = 
\begin{bmatrix}
2 & -3 \\
-3 & 5
\end{bmatrix}
$.
\vspace{5mm}
\\
The last piece we need to evaluate before solving for the joint pdf is $ \displaystyle ||\bm{\Sigma}|| $ .
\vspace{5mm}
\\
$ \displaystyle 
||\bm{\Sigma}|| = 
\left|\left|
\begin{bmatrix}
5 & 3 \\
3 & 2
\end{bmatrix}
\right|\right| = 
|10 -9| = |1|=1
$.
\vspace{5mm}
\\
We can now solve for $ \displaystyle f_{Y_1,Y_2}(y_1,y_2) = 
\frac{e^{-\frac{(\bm{y-\mu)}^{T}\bm{\Sigma}^{-1}(\bm{y-\mu)}}{2}}}{(2\pi)^{\frac{n}{2}}\sqrt{||\bm{\Sigma}||}} = 
\frac{e^{-\frac{(\bm{y)}^{T}\bm{\Sigma}^{-1}(\bm{y)}}{2}}}{(2\pi)^{\frac{2}{2}}\sqrt{1}} = 
\frac{e^{-\frac{(\bm{y)}^{T}\bm{\Sigma}^{-1}(\bm{y)}}{2}}}{2\pi}
$.
\vspace{5mm}
\\
$\displaystyle 
\bm{y}^{T}\bm{\Sigma}^{-1}\bm{y} = 
\begin{bmatrix}
y_{1} & y_{2} 
\end{bmatrix}
\begin{bmatrix}
2 & -3 \\
-3 & 5
\end{bmatrix}
\begin{bmatrix}
y_{1} \\
y_{2}
\end{bmatrix} = 
\begin{bmatrix}
2y_{1} - 3y_{2} & -3y_{1} + 5y_{2}
\end{bmatrix}
\begin{bmatrix}
y_{1} \\
y_{2}
\end{bmatrix} 
$.
\vspace{5mm}
\\
$ \displaystyle
= 2y_{1}^{2} - 3y_{2}y_{1} -3y_{1}y_{2} + 5y_{2}^{2}
= 2y_{1}^{2} - 6y_{1}y_{2} + 5y_{2}^{2}
$.
\vspace{5mm}
\\
By Substitution, $ \displaystyle f_{Y_1,Y_2}(y_1,y_2) =
\frac{1}{2\pi}\exp\left(\frac{-2y_{1}^{2} + 6y_{1}y_{2} - 5y_{2}^{2}}{2}\right).
$

```

---

```{=latex}
\newpage
(b)  Find the marginal pdf $f_{Y_2}(y_2)$.  Don't use integration -- you can derive the needed pdf doing only the simplest  arithmetic using some facts from MTH 372.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
We have one equation, $\displaystyle 
\bm{Y} = 
Y_{2} = 
A\bm{Z} + \bm{\mu} =
\begin{bmatrix}
1 & -1
\end{bmatrix}
\begin{bmatrix}
Z_{1} \\
Z_{2}
\end{bmatrix} + 
\begin{bmatrix}
0 \\
0
\end{bmatrix}
= Z_1-Z_2
$.
\vspace{5mm}
\\
We can solve for $ \displaystyle 
\bm{\Sigma} = \bm{AA^{T}} =
\begin{bmatrix}
1 & -1
\end{bmatrix}
\begin{bmatrix}
1 \\
-1 
\end{bmatrix} = 
2 = \bm{\Sigma}.
$
\vspace{5mm}
\\
We can now evaluate $ \displaystyle 
\bm{\Sigma}^{-1} 
= \frac{1}{2}.
$
\vspace{5mm}
\\
The last piece we need to evaluate before solving for the joint pdf is $ \displaystyle ||\bm{\Sigma}|| = 2 $.
\vspace{5mm}
\\
We can now solve for $ \displaystyle f_{Y_2}(y_2) = 
\frac{e^{-\frac{(\bm{y-\mu)}^{T}\bm{\Sigma}^{-1}(\bm{y-\mu)}}{2}}}{(2\pi)^{\frac{n}{2}}\sqrt{||\bm{\Sigma}||}} = 
\frac{e^{-\frac{(\bm{y)}^{T}\bm{\Sigma}^{-1}(\bm{y)}}{2}}}{(2\pi)^{\frac{1}{2}}\sqrt{2}} = 
\frac{e^{-\frac{(\bm{y)}^{T}\bm{\Sigma}^{-1}(\bm{y)}}{2}}}{\sqrt{2}\sqrt{2\pi}}.
$
\vspace{5mm}
\\
$\displaystyle 
\bm{y}^{T}\bm{\Sigma}^{-1}\bm{y} = 
y_{2}\frac{1}{2}y_{2} = \frac{y_{2}^{2}}{2}.
$
\vspace{5mm}
\\
By Substitution, $ \displaystyle f_{Y_2}(y_2) =
\frac{1}{\sqrt{2}\sqrt{2\pi}}\exp\left({\frac{-y_{2}^{2}}{4}}\right).
$
```

---

```{=latex}
\newpage
(c)  Find the conditional pdf of $Y_1$ given $Y_2=1$, that is, \ $f_{Y_1|Y_2}(y_1|1)$.   Use (a) and (b), and do the necessary division.  By completing the square,  identify by name -- {\em including parameters} -- the required conditional pdf.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
$ \displaystyle 
f_{Y_1|Y_2}(y_1|y_2) = \frac{f_{Y_1,Y_2}(y_1,y_2)}{f_{Y_2}(y_2)} = 
\frac{\frac{1}{2\pi}\exp\left(\frac{-2y_{1}^{2} + 6y_{1}y_{2} - 5y_{2}^{2}}{2}\right)}{\frac{1}{\sqrt{2}\sqrt{2\pi}}\exp\left({\frac{-y_{2}^{2}}{4}}\right)} = 
\frac{\sqrt{2}\exp\left(\frac{-2y_{1}^{2} + 6y_{1}y_{2} - 5y_{2}^{2}}{2}\right)}{\sqrt{2\pi}\exp\left({\frac{-y_{2}^{2}}{4}}\right)}.
\vspace{5mm}
\\ =
\frac{\sqrt{2}\exp\left(\frac{-4y_{1}^{2} + 12y_{1}y_{2} - 10y_{2}^{2}}{4} - \frac{-y_{2}^{2}}{4}\right)}{\sqrt{2\pi}} = 
\frac{\sqrt{2}\exp\left(\frac{-4y_{1}^{2} + 12y_{1}y_{2} - 9y_{2}^{2}}{4} \right)}{\sqrt{2\pi}}.
\vspace{5mm}
\\
f_{Y_1|Y_2}(y_1|y_2 = 1) = \frac{f_{Y_1,Y_2}(y_1,y_2 = 1)}{f_{Y_2}(y_2 = 1)} = 
\frac{\sqrt{2}\exp\left(\frac{-4y_{1}^{2} + 12y_{1}(1) - 9(1)^{2}}{4} \right)}{\sqrt{2\pi}} = 
\frac{\sqrt{2}\exp\left(\frac{-4y_{1}^{2} + 12y_{1} - 9}{4} \right)}{\sqrt{2\pi}}.
\vspace{5mm}
\\ =
\frac{\sqrt{2}\exp\left(-(\frac{1}{2})(\frac{4y_{1}^{2} - 12y_{1} + 9}{2}) \right)}{\sqrt{2\pi}} = 
\frac{\sqrt{2}\exp\left(-(\frac{1}{2})(2y_{1}^{2} - 6y_{1} + 4.5) \right)}{\sqrt{2\pi}} = 
\frac{\sqrt{2}\exp\left(-(y_{1}^{2} - 3y_{1} + 2.25) \right)}{\sqrt{2\pi}}.
\vspace{5mm}
\\ =
\frac{\sqrt{2}\exp\left(-(y_{1} - 1.5)^2 \right)}{\sqrt{2\pi}} $.
\vspace{5mm}
\\
It is now worthwhile to considerd the pdf of Random Variable $ X \thicksim N(\mu, \sigma^2) $.
\vspace{5mm}
\\ $ \displaystyle
f_{X}(x) = \frac{1}{\sigma\sqrt{2\pi}}\exp\left(-\frac{1}{2\sigma^2}(x-\mu)^2\right) $.
\vspace{5mm}
\\ 
Under close inspection, we can see that our above distribution for $ f_{Y_1|Y_2}(y_1|y_2=1) $ 
is normal, taking $\displaystyle \sigma = \frac{1}{\sqrt{2}}$, $\displaystyle \sigma^2 = \frac{1}{2}$, and $\displaystyle \mu = 1.5$.

```

---

```{=latex}
\newpage
```

```{=latex}
2.  Suppose $Z_1,Z_2,\ldots,Z_6$ are independent standard normal random variables.   

\hrulefill 

\vspace{5mm}
```

```{=latex}
(a)  Find a number $a$ such that $P(-a<3Z_1+2Z_2-4Z_3<a)=.99$.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
Let $A = 3Z_1+2Z_2-4Z_3 $.

$A \thicksim N(0,(3^2 + 2^2 + 4^2)) \thicksim N(0,(9 + 4 + 16)) \thicksim N(0,29)$.

As $ V(A) = 29 $, $ \sigma_{A} = \sqrt{29} $.

We now wish to have probabilities for $ -a $ corresponding to $ 0.005 $ and $ a $ corresponding to $ 0.995 $.
\vspace{5mm}
```

```{r, size='large'}
qnorm(p = c(0.005, 0.995), mean = 0, sd = sqrt(29))
```

```{=latex}
\vspace{5mm}
We can see here that $ a = 13.87127 $ is the solution.
```

---

```{=latex}
\vspace{5mm}
(b)  Find numbers $a,b$ such that $P(a<Z_1^2+Z_2^2+\cdots +Z_6^2 <b)=.99$.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
Let $B = Z_1^2+Z_2^2+Z_3^2+Z_4^2+Z_5^2+Z_6^2 \\
B \thicksim \chi_6^2$.

Let us make the generalizing assumption $ a = 0$.

We now wish to have probabilities for $ a $ corresponding to $ 0.0 $ and $ b $ corresponding to $ 0.99 $.
\vspace{5mm}
```

```{r, size='large'}
qchisq(p = c(0.0, 0.99), df = 6)
```

```{=latex}
\vspace{5mm}
We can see here that $ a = 0.0 $ and $ b = 16.81189 $ is one solution.
```

---

```{=latex}
\newpage
\vspace{5mm}
(c) Find a numbers $a$ such that $\displaystyle P\left( -a < \frac{Z_1}{\sqrt{Z^2_2+Z^2_3+\cdots+Z^2_6}} < a \right)=.99$.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
Let $\displaystyle C = \frac{Z_1}{\sqrt{Z^2_2+Z^2_3+\cdots+Z^2_6}} $.

\vspace{2.5mm}
We will leverage the following two points to solve this problem: 
\vspace{2.5mm}
\begin{itemize}
  \item $\displaystyle C\sqrt{5} = \frac{Z_1\sqrt{6}}{\sqrt{Z^2_2+Z^2_3+\cdots+Z^2_6}} \thicksim T_5$.
  \vspace{2.5mm}
  \item $\displaystyle P\left( -a < \frac{Z_1}{\sqrt{Z^2_2+Z^2_3+\cdots+Z^2_6}} < a \right) = 
  P\left( -a\sqrt{5} < \frac{Z_1\sqrt{5}}{\sqrt{Z^2_2+Z^2_3+\cdots+Z^2_6}} < a\sqrt{5} \right)$.
\end{itemize}
\vspace{5mm}
We now wish to have probabilities for $ -a\sqrt{5} $ corresponding to $ 0.005 $ and $ a\sqrt{5} $ corresponding to $ 0.995 $.

In particular, we will solve $\displaystyle P\left( -a\sqrt{5} < T_5 < a\sqrt{5} \right) = 0.99$. 
\vspace{5mm}
```

```{r, size='large'}
a_sqrt_5 <- qt(p = c(0.005, 0.995), df = 5)
a_sqrt_5
a_sqrt_5 / sqrt(5)
```

```{=latex}
\vspace{5mm}
We can see here that $ a = 1.803229 $ is the solution.
```

---

```{=latex}
\newpage
\vspace{5mm}
(d) Find numbers $a,b$ such that: $\displaystyle P\left( a < \frac{Z^2_1+Z^2_2+Z^2_3+Z^2_4}{Z^2_5+Z^2_6} < b \right)=.99$.
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
Let $\displaystyle D = \frac{Z^2_1+Z^2_2+Z^2_3+Z^2_4}{Z^2_5+Z^2_6} $.

\vspace{2.5mm}
We will leverage the following two points to solve this problem: 
\vspace{2.5mm}
\begin{itemize}
  \item $\displaystyle \frac{D}{2} = \frac{1}{2} \cdot \frac{Z^2_1+Z^2_2+Z^2_3+Z^2_4}{Z^2_5+Z^2_6} 
  = \frac{2\chi_4}{4\chi_2} \thicksim F_{4,2}$.
  \vspace{2.5mm}
  \item $\displaystyle P\left( a < \frac{Z^2_1+Z^2_2+Z^2_3+Z^2_4}{Z^2_5+Z^2_6} < b \right) = 
  P\left( \frac{a}{2} < \frac{1}{2} \cdot \frac{Z^2_1+Z^2_2+Z^2_3+Z^2_4}{Z^2_5+Z^2_6} < \frac{b}{2} \right)$.
\end{itemize}
\vspace{5mm}
Let us make the generalizing assumption $ a = 0$.

We now wish to have probabilities for $ a $ corresponding to $ 0.0 $ and $ b $ corresponding to $ 0.99 $.

In particular, we will solve $\displaystyle P\left( 0 < F_{4,2} < \frac{b}{2} \right) = 0.99$. 
\vspace{5mm}
```

```{r, size='large'}
ab_halved <- qf(p = c(0.0, 0.99), df1 = 4, df2 = 2)
ab_halved
ab_halved * 2
```

```{=latex}
\vspace{5mm}
We can see here that $ a = 0.0 $ and $ b = 198.4987 $ is one solution.
```

---

```{=latex}
\newpage
```

```{=latex}
% https://online.stat.psu.edu/stat414/lesson/26/26.3

3.  Let $X_1,X_2,\ldots,X_8$ be independent normal($\mu,\sigma^2$)  random variables, 

\noindent $\displaystyle \overline{X} = \frac{X_1+X_2+\ldots+X_8}{8}$, and $\displaystyle S^2 = \frac17\sum_{i=1}^8 (X_i- \overline{X})^2$.

Find a number $a$ such that $\displaystyle  P\left( -a<  \frac{\overline{X} - \mu}{S}  <a\right) =.99$. 

\hrulefill 
\vspace{10mm}
\\
\textit{Solution}:

\vspace{2.5mm}
We will leverage the following from class in this solution... 
\vspace{2.5mm}
\begin{itemize}
  \item $ \displaystyle \overline{X} \thicksim N(\mu, \frac{\sigma^2}{n}) $.
  \vspace{2.5mm}
  \item $ \displaystyle \frac{(n-1)S^2}{\sigma^2} = \frac{1}{\sigma^2}\sum_{i=1}^n (X_{i} - \overline{X})^{2} \thicksim \chi_{n-1}^2 $.
  \vspace{2.5mm}
  \item $\overline{X}$ and $S$ are independent.
\end{itemize}
\vspace{2.5mm}

Letting $ \displaystyle Y = \frac{\overline{X} - \mu}{S} $.

Under close inspection, for arbitrary $n$, we can see the following... 
\vspace{2.5mm}
\\
$ \displaystyle 
Y \cdot \sqrt{n} = 
\frac{\overline{X} - \mu}{\color{purple}S\color{black}} \cdot \sqrt{n} \cdot \frac{\color{purple}\sigma}{\color{black}\sigma} \cdot \frac{\color{blue}\sqrt{n-1}}{\color{purple}\sqrt{n-1}\color{black}} = 
\frac{(\overline{X} - \mu)\sqrt{n}}{\sigma} \cdot \color{purple} \frac{\sqrt{\sigma^2}}{\sqrt{S^2}\sqrt{n-1}} \color{black} \cdot \color{blue} \frac{\sqrt{n-1}}{1} \color{black} \thicksim 
Z \cdot \frac{\color{blue}\sqrt{n-1}\color{black}}{\color{purple}\sqrt{\chi_{n-1}^{2}}\color{black}} \thicksim 
T_{n-1} $.

\vspace{2.5mm}
We will thus leverage the following two points to solve this problem: 
\vspace{2.5mm}
\begin{itemize}
  \item $\displaystyle Y\sqrt{8} = \frac{(\overline{X} - \mu)\sqrt{8}}{\sigma} \cdot \color{purple} \frac{\sqrt{\sigma^2}}{\sqrt{S^2}\sqrt{7}} \color{black} \cdot \color{blue} \frac{\sqrt{7}}{1} \color{black} \thicksim Z \cdot \frac{\color{blue}\sqrt{7}\color{black}}{\color{purple}\sqrt{\chi_{7}^{2}}\color{black}} \thicksim  T_7$.
  \vspace{2.5mm}
  \item $\displaystyle P\left( -a < \frac{\overline{X} - \mu}{S} < a \right) = 
  P\left( -a\sqrt{8} < \frac{(\overline{X} - \mu)\sqrt{8}}{\sigma} \cdot \color{purple} \frac{\sqrt{\sigma^2}}{\sqrt{S^2}\sqrt{7}} \color{black} \cdot \color{blue} \frac{\sqrt{7}}{1} \color{black} < a\sqrt{8} \right)$.
\end{itemize}
\vspace{5mm}
We now wish to have probabilities for $ -a\sqrt{8} $ corresponding to $ 0.005 $ and $ a\sqrt{8} $ corresponding to $ 0.995 $.

In particular, we will solve $\displaystyle P\left( -a\sqrt{8} < T_7 < a\sqrt{8} \right) = 0.99$. 
\vspace{5mm}
```

```{r, size='large'}
a_sqrt_8 <- qt(p = c(0.005, 0.995), df = 7)
a_sqrt_8
a_sqrt_8 / sqrt(8)
```

```{=latex}
\vspace{5mm}
We can see here that $ a = 1.237254 $ is the solution.
```

---

```{=latex}
\newpage
```

